using MermaidSharp.Enums;

namespace MermaidSharp.AutoDiagram.Constants
{
    /// <summary>
    /// Provides constants used for class diagram generation.
    /// </summary>
    public static class ClassDiagramConstants
    {
        /// <summary>
        /// Represents the names of the auto-generated program classes to exclude.
        /// </summary>
        public static readonly string[] AutoGeneratedProgramClasses = new string[] { "AutoGeneratedProgram" };

        /// <summary>
        /// Defines the order of class property visibility levels for sorting purposes in Mermaid diagrams.
        /// </summary>
        public static readonly ClassPropertyVisibility[] PropertiesSortOrder = new ClassPropertyVisibility[]
        {
            ClassPropertyVisibility.Private,
            ClassPropertyVisibility.Protected,
            ClassPropertyVisibility.Internal,
            ClassPropertyVisibility.Public
        };
    }
}
