using MermaidSharp.AutoDiagram.Enums;
using MermaidSharp.AutoDiagram.Extensions;
using MermaidSharp.AutoDiagram.Models.ClassDiagrams;
using MermaidSharp.AutoDiagram.Options;
using MermaidSharp.Enums;
using System;

namespace MermaidSharp.AutoDiagram
{
    /// <summary>
    /// Provides options to control the content generated in a class diagram from reflection.
    /// </summary>
    public class ClassDiagramOptions
    {
        /// <summary>
        /// Gets or sets the visibility level of class properties to include.
        /// </summary>
        /// <remarks>Use this property to control which class property visibilities are included when
        /// generating diagrams or processing class metadata. The default value includes all visibility
        /// levels.</remarks>
        public ClassPropertyVisibility IncludeClassesVisibility { get; set; } = ClassPropertyVisibilityExtensions.All;

        /// <summary>
        /// Gets or sets a predicate used to filter which types are included in the diagram.
        /// When null, all types are included.
        /// </summary>
        public Func<Type, bool> AssemblyClassFilter { get; set; } = DefaultTypeFilter;

        /// <summary>
        /// Gets the options used to configure property generation for the class.
        /// </summary>
        public ClassPropertyOptions PropertyOptions { get; set; } = new ClassPropertyOptions();

        /// <summary>
        /// Gets the options used to configure method generation for the class.
        /// </summary>
        public ClassMethodOptions MethodOptions { get; set; } = new ClassMethodOptions();

        /// <summary>
        /// Gets the options used to configure link generation for the class.
        /// </summary>
        public ClassLinkOptions LinkOptions { get; set; } = new ClassLinkOptions();

        private static bool DefaultTypeFilter(Type t)
        {
            return t?.FullName != "AutoGeneratedProgram";
        }
    }
}
